apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: persistentvolumeclaims
spec:
  group: ""
  scope: Namespaced
  names:
    kind: PersistentVolumeClaim
    plural: persistentvolumeclaims
  versions:
    - name: v1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              properties:
                accessModes:
                  type: array
                  items:
                    type: string
                storageClassName:
                  type: string
                volumeMode:
                  type: string
                volumeName:
                  type: string
                selector:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        storage:
                          type: string
                      additionalProperties: true
                  additionalProperties: true
              additionalProperties: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          additionalProperties: false
